# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plantmap_dialog_base.ui'
#
# Created: Tue Mar  1 09:35:58 2016
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PlantMapDialogBase(object):
    def setupUi(self, PlantMapDialogBase):
        PlantMapDialogBase.setObjectName(_fromUtf8("PlantMapDialogBase"))
        PlantMapDialogBase.resize(837, 846)
        PlantMapDialogBase.setMaximumSize(QtCore.QSize(16777215, 1400))
        self.gridLayout_3 = QtGui.QGridLayout(PlantMapDialogBase)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(PlantMapDialogBase)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.stackedWidget = QtGui.QStackedWidget(self.tab_3)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.editcreat_proj = QtGui.QWidget()
        self.editcreat_proj.setObjectName(_fromUtf8("editcreat_proj"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.editcreat_proj)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_12.addItem(spacerItem)
        self.textEdit = QtGui.QTextEdit(self.editcreat_proj)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_12.addWidget(self.textEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_12.addItem(spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_12.addItem(spacerItem2)
        self.UI_buttonCreateProjectFrom = QtGui.QPushButton(self.editcreat_proj)
        self.UI_buttonCreateProjectFrom.setObjectName(_fromUtf8("UI_buttonCreateProjectFrom"))
        self.verticalLayout_12.addWidget(self.UI_buttonCreateProjectFrom)
        self.UI_buttonCreateProject = QtGui.QPushButton(self.editcreat_proj)
        self.UI_buttonCreateProject.setObjectName(_fromUtf8("UI_buttonCreateProject"))
        self.verticalLayout_12.addWidget(self.UI_buttonCreateProject)
        self.UI_buttonEditProject = QtGui.QPushButton(self.editcreat_proj)
        self.UI_buttonEditProject.setObjectName(_fromUtf8("UI_buttonEditProject"))
        self.verticalLayout_12.addWidget(self.UI_buttonEditProject)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_12.addItem(spacerItem3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_12.addItem(spacerItem4)
        self.stackedWidget.addWidget(self.editcreat_proj)
        self.proj = QtGui.QWidget()
        self.proj.setObjectName(_fromUtf8("proj"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.proj)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox = QtGui.QGroupBox(self.proj)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.scrollArea = QtGui.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 736, 377))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_49 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_2.addWidget(self.label_49, 4, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_2.addWidget(self.label_32, 8, 0, 1, 1)
        self.label_51 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_2.addWidget(self.label_51, 6, 0, 1, 1)
        self.UI_contactEmail = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.UI_contactEmail.setText(_fromUtf8(""))
        self.UI_contactEmail.setObjectName(_fromUtf8("UI_contactEmail"))
        self.gridLayout_2.addWidget(self.UI_contactEmail, 7, 0, 1, 1)
        self.label_63 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_2.addWidget(self.label_63, 0, 0, 1, 1)
        self.widget_2 = QtGui.QWidget(self.scrollAreaWidgetContents_3)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_50 = QtGui.QLabel(self.widget_2)
        self.label_50.setMinimumSize(QtCore.QSize(100, 0))
        self.label_50.setMaximumSize(QtCore.QSize(50, 20))
        self.label_50.setScaledContents(False)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout.addWidget(self.label_50)
        self.UI_startDate = QtGui.QDateEdit(self.widget_2)
        self.UI_startDate.setMaximumSize(QtCore.QSize(150, 20))
        self.UI_startDate.setCalendarPopup(True)
        self.UI_startDate.setObjectName(_fromUtf8("UI_startDate"))
        self.horizontalLayout.addWidget(self.UI_startDate)
        self.UI_endDate = QtGui.QDateEdit(self.widget_2)
        self.UI_endDate.setMaximumSize(QtCore.QSize(150, 20))
        self.UI_endDate.setBaseSize(QtCore.QSize(0, 0))
        self.UI_endDate.setCalendarPopup(True)
        self.UI_endDate.setObjectName(_fromUtf8("UI_endDate"))
        self.horizontalLayout.addWidget(self.UI_endDate)
        self.gridLayout_2.addWidget(self.widget_2, 10, 0, 1, 1)
        self.UI_contactName = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.UI_contactName.setObjectName(_fromUtf8("UI_contactName"))
        self.gridLayout_2.addWidget(self.UI_contactName, 5, 0, 1, 1)
        self.UI_projectName = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.UI_projectName.setText(_fromUtf8(""))
        self.UI_projectName.setObjectName(_fromUtf8("UI_projectName"))
        self.gridLayout_2.addWidget(self.UI_projectName, 1, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 2, 0, 1, 1)
        self.UI_cbnOrganisation = QtGui.QComboBox(self.scrollAreaWidgetContents_3)
        self.UI_cbnOrganisation.setObjectName(_fromUtf8("UI_cbnOrganisation"))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.UI_cbnOrganisation.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.UI_cbnOrganisation, 9, 0, 1, 1)
        self.UI_projectDescription = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents_3)
        self.UI_projectDescription.setObjectName(_fromUtf8("UI_projectDescription"))
        self.gridLayout_2.addWidget(self.UI_projectDescription, 3, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 12, 0, 1, 1)
        self.UI_projectVersion = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.UI_projectVersion.setObjectName(_fromUtf8("UI_projectVersion"))
        self.gridLayout_2.addWidget(self.UI_projectVersion, 13, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.proj)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.UI_dataGeneaology = QtGui.QScrollArea(self.groupBox_2)
        self.UI_dataGeneaology.setWidgetResizable(True)
        self.UI_dataGeneaology.setObjectName(_fromUtf8("UI_dataGeneaology"))
        self.scrollAreaWidgetContents_5 = QtGui.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 736, 462))
        self.scrollAreaWidgetContents_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_52 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.verticalLayout_6.addWidget(self.label_52)
        self.UI_thesaurusISO = QtGui.QComboBox(self.scrollAreaWidgetContents_5)
        self.UI_thesaurusISO.setObjectName(_fromUtf8("UI_thesaurusISO"))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.UI_thesaurusISO.addItem(_fromUtf8(""))
        self.verticalLayout_6.addWidget(self.UI_thesaurusISO)
        self.label_53 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.verticalLayout_6.addWidget(self.label_53)
        self.UI_thesaurusInspire = QtGui.QComboBox(self.scrollAreaWidgetContents_5)
        self.UI_thesaurusInspire.setObjectName(_fromUtf8("UI_thesaurusInspire"))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.UI_thesaurusInspire.addItem(_fromUtf8(""))
        self.verticalLayout_6.addWidget(self.UI_thesaurusInspire)
        self.label_55 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.verticalLayout_6.addWidget(self.label_55)
        self.UI_keywords = QtGui.QLineEdit(self.scrollAreaWidgetContents_5)
        self.UI_keywords.setObjectName(_fromUtf8("UI_keywords"))
        self.verticalLayout_6.addWidget(self.UI_keywords)
        self.label_56 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.verticalLayout_6.addWidget(self.label_56)
        self.UI_contact = QtGui.QLineEdit(self.scrollAreaWidgetContents_5)
        self.UI_contact.setObjectName(_fromUtf8("UI_contact"))
        self.verticalLayout_6.addWidget(self.UI_contact)
        self.label_57 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.verticalLayout_6.addWidget(self.label_57)
        self.UI_dataOwner = QtGui.QLineEdit(self.scrollAreaWidgetContents_5)
        self.UI_dataOwner.setObjectName(_fromUtf8("UI_dataOwner"))
        self.verticalLayout_6.addWidget(self.UI_dataOwner)
        self.label_58 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.verticalLayout_6.addWidget(self.label_58)
        self.UI_genealogyData = QtGui.QLineEdit(self.scrollAreaWidgetContents_5)
        self.UI_genealogyData.setObjectName(_fromUtf8("UI_genealogyData"))
        self.verticalLayout_6.addWidget(self.UI_genealogyData)
        self.label_59 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.verticalLayout_6.addWidget(self.label_59)
        self.UI_cbnManager = QtGui.QLineEdit(self.scrollAreaWidgetContents_5)
        self.UI_cbnManager.setObjectName(_fromUtf8("UI_cbnManager"))
        self.verticalLayout_6.addWidget(self.UI_cbnManager)
        self.label_60 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.verticalLayout_6.addWidget(self.label_60)
        self.UI_updateFrequency = QtGui.QLineEdit(self.scrollAreaWidgetContents_5)
        self.UI_updateFrequency.setObjectName(_fromUtf8("UI_updateFrequency"))
        self.verticalLayout_6.addWidget(self.UI_updateFrequency)
        self.label_61 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.verticalLayout_6.addWidget(self.label_61)
        self.UI_usageLimit = QtGui.QLineEdit(self.scrollAreaWidgetContents_5)
        self.UI_usageLimit.setObjectName(_fromUtf8("UI_usageLimit"))
        self.verticalLayout_6.addWidget(self.UI_usageLimit)
        self.label_62 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.verticalLayout_6.addWidget(self.label_62)
        self.UI_dataState = QtGui.QLineEdit(self.scrollAreaWidgetContents_5)
        self.UI_dataState.setObjectName(_fromUtf8("UI_dataState"))
        self.verticalLayout_6.addWidget(self.UI_dataState)
        self.UI_dataGeneaology.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout.addWidget(self.UI_dataGeneaology)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        self.verticalLayout_15.addLayout(self.verticalLayout_8)
        self.UI_buttonCreate = QtGui.QPushButton(self.proj)
        self.UI_buttonCreate.setObjectName(_fromUtf8("UI_buttonCreate"))
        self.verticalLayout_15.addWidget(self.UI_buttonCreate)
        self.UI_buttonPrevious = QtGui.QPushButton(self.proj)
        self.UI_buttonPrevious.setObjectName(_fromUtf8("UI_buttonPrevious"))
        self.verticalLayout_15.addWidget(self.UI_buttonPrevious)
        self.stackedWidget.addWidget(self.proj)
        self.createProjectWithAnotherOne = QtGui.QWidget()
        self.createProjectWithAnotherOne.setObjectName(_fromUtf8("createProjectWithAnotherOne"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.createProjectWithAnotherOne)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.groupBox_5 = QtGui.QGroupBox(self.createProjectWithAnotherOne)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame = QtGui.QFrame(self.groupBox_5)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.UI_comboProjectSelection = QtGui.QComboBox(self.frame)
        self.UI_comboProjectSelection.setObjectName(_fromUtf8("UI_comboProjectSelection"))
        self.verticalLayout_17.addWidget(self.UI_comboProjectSelection)
        self.UI_displayProjectName = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.UI_displayProjectName.setFont(font)
        self.UI_displayProjectName.setText(_fromUtf8(""))
        self.UI_displayProjectName.setObjectName(_fromUtf8("UI_displayProjectName"))
        self.verticalLayout_17.addWidget(self.UI_displayProjectName)
        self.UI_displayProjectDescription = QtGui.QLabel(self.frame)
        self.UI_displayProjectDescription.setText(_fromUtf8(""))
        self.UI_displayProjectDescription.setObjectName(_fromUtf8("UI_displayProjectDescription"))
        self.verticalLayout_17.addWidget(self.UI_displayProjectDescription)
        self.UI_tabProject = QtGui.QTableWidget(self.frame)
        self.UI_tabProject.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.UI_tabProject.setObjectName(_fromUtf8("UI_tabProject"))
        self.UI_tabProject.setColumnCount(2)
        self.UI_tabProject.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.UI_tabProject.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.UI_tabProject.setHorizontalHeaderItem(1, item)
        self.UI_tabProject.horizontalHeader().setDefaultSectionSize(310)
        self.verticalLayout_17.addWidget(self.UI_tabProject)
        self.UI_validationProject = QtGui.QPushButton(self.frame)
        self.UI_validationProject.setObjectName(_fromUtf8("UI_validationProject"))
        self.verticalLayout_17.addWidget(self.UI_validationProject)
        self.UI_cancelProject = QtGui.QPushButton(self.frame)
        self.UI_cancelProject.setObjectName(_fromUtf8("UI_cancelProject"))
        self.verticalLayout_17.addWidget(self.UI_cancelProject)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout_9.addWidget(self.groupBox_5)
        self.stackedWidget.addWidget(self.createProjectWithAnotherOne)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_mapgenerator = QtGui.QWidget()
        self.tab_mapgenerator.setObjectName(_fromUtf8("tab_mapgenerator"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_mapgenerator)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.frame_mapgenerator = QtGui.QFrame(self.tab_mapgenerator)
        self.frame_mapgenerator.setObjectName(_fromUtf8("frame_mapgenerator"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_mapgenerator)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.UI_generateMapButton = QtGui.QPushButton(self.frame_mapgenerator)
        self.UI_generateMapButton.setObjectName(_fromUtf8("UI_generateMapButton"))
        self.gridLayout_7.addWidget(self.UI_generateMapButton, 2, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.groupBox_3 = QtGui.QGroupBox(self.frame_mapgenerator)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_3.setMouseTracking(False)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.UI_taxonTab = QtGui.QTableWidget(self.groupBox_3)
        self.UI_taxonTab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.UI_taxonTab.setFrameShape(QtGui.QFrame.StyledPanel)
        self.UI_taxonTab.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.UI_taxonTab.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.UI_taxonTab.setAlternatingRowColors(False)
        self.UI_taxonTab.setGridStyle(QtCore.Qt.SolidLine)
        self.UI_taxonTab.setCornerButtonEnabled(False)
        self.UI_taxonTab.setObjectName(_fromUtf8("UI_taxonTab"))
        self.UI_taxonTab.setColumnCount(4)
        self.UI_taxonTab.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.UI_taxonTab.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.UI_taxonTab.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.UI_taxonTab.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.UI_taxonTab.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.UI_taxonTab)
        self.widget_4 = QtGui.QWidget(self.groupBox_3)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.UI_buttonRemoveAll = QtGui.QPushButton(self.widget_4)
        self.UI_buttonRemoveAll.setAutoDefault(False)
        self.UI_buttonRemoveAll.setObjectName(_fromUtf8("UI_buttonRemoveAll"))
        self.gridLayout_5.addWidget(self.UI_buttonRemoveAll, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.UI_taxonID = QtGui.QLineEdit(self.widget_4)
        self.UI_taxonID.setObjectName(_fromUtf8("UI_taxonID"))
        self.gridLayout_5.addWidget(self.UI_taxonID, 1, 0, 1, 1)
        self.UI_validateTaxonList = QtGui.QPushButton(self.widget_4)
        self.UI_validateTaxonList.setMinimumSize(QtCore.QSize(145, 0))
        self.UI_validateTaxonList.setAutoDefault(False)
        self.UI_validateTaxonList.setObjectName(_fromUtf8("UI_validateTaxonList"))
        self.gridLayout_5.addWidget(self.UI_validateTaxonList, 1, 2, 1, 1)
        self.UI_validateTaxonID = QtGui.QPushButton(self.widget_4)
        self.UI_validateTaxonID.setAutoDefault(True)
        self.UI_validateTaxonID.setObjectName(_fromUtf8("UI_validateTaxonID"))
        self.gridLayout_5.addWidget(self.UI_validateTaxonID, 1, 1, 1, 1)
        self.UI_deepValidation = QtGui.QPushButton(self.widget_4)
        self.UI_deepValidation.setAutoDefault(False)
        self.UI_deepValidation.setObjectName(_fromUtf8("UI_deepValidation"))
        self.gridLayout_5.addWidget(self.UI_deepValidation, 1, 4, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_5)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.gridLayout_8.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.mGroupBox_2 = gui.QgsCollapsibleGroupBox(self.frame_mapgenerator)
        self.mGroupBox_2.setProperty("collapsed", False)
        self.mGroupBox_2.setObjectName(_fromUtf8("mGroupBox_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.mGroupBox_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox1 = QtGui.QGroupBox(self.mGroupBox_2)
        self.groupBox1.setTitle(_fromUtf8(""))
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.groupBox1)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.UI_composerName = QtGui.QComboBox(self.groupBox1)
        self.UI_composerName.setObjectName(_fromUtf8("UI_composerName"))
        self.gridLayout_6.addWidget(self.UI_composerName, 1, 0, 1, 1)
        self.label_119 = QtGui.QLabel(self.groupBox1)
        self.label_119.setObjectName(_fromUtf8("label_119"))
        self.gridLayout_6.addWidget(self.label_119, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.UI_extensionMap = QtGui.QComboBox(self.groupBox1)
        self.UI_extensionMap.setObjectName(_fromUtf8("UI_extensionMap"))
        self.UI_extensionMap.addItem(_fromUtf8(""))
        self.UI_extensionMap.addItem(_fromUtf8(""))
        self.UI_extensionMap.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.UI_extensionMap, 1, 1, 1, 1)
        self.verticalLayout_18.addLayout(self.gridLayout_6)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.UI_mapName = QtGui.QLineEdit(self.groupBox1)
        self.UI_mapName.setObjectName(_fromUtf8("UI_mapName"))
        self.gridLayout.addWidget(self.UI_mapName, 3, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.UI_storagePathButton = QtGui.QToolButton(self.groupBox1)
        self.UI_storagePathButton.setObjectName(_fromUtf8("UI_storagePathButton"))
        self.gridLayout.addWidget(self.UI_storagePathButton, 3, 2, 1, 1)
        self.UI_storagePath = QtGui.QLineEdit(self.groupBox1)
        self.UI_storagePath.setPlaceholderText(_fromUtf8(""))
        self.UI_storagePath.setObjectName(_fromUtf8("UI_storagePath"))
        self.gridLayout.addWidget(self.UI_storagePath, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.verticalLayout_18.addLayout(self.gridLayout)
        self.horizontalLayout_4.addWidget(self.groupBox1)
        self.gridLayout_8.addWidget(self.mGroupBox_2, 3, 0, 1, 1)
        self.mGroupBox = gui.QgsCollapsibleGroupBox(self.frame_mapgenerator)
        self.mGroupBox.setProperty("collapsed", False)
        self.mGroupBox.setObjectName(_fromUtf8("mGroupBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.mGroupBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.groupBox2 = QtGui.QGroupBox(self.mGroupBox)
        self.groupBox2.setTitle(_fromUtf8(""))
        self.groupBox2.setObjectName(_fromUtf8("groupBox2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.widget_3 = QtGui.QWidget(self.groupBox2)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_11 = QtGui.QLabel(self.widget_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_5.addWidget(self.label_11)
        self.UI_linkExpression = QtGui.QLabel(self.widget_3)
        self.UI_linkExpression.setObjectName(_fromUtf8("UI_linkExpression"))
        self.horizontalLayout_5.addWidget(self.UI_linkExpression)
        self.label_13 = QtGui.QLabel(self.widget_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_5.addWidget(self.label_13)
        self.gridLayout_4.addWidget(self.widget_3, 6, 0, 1, 1)
        self.UI_taxonLayer = QtGui.QComboBox(self.groupBox2)
        self.UI_taxonLayer.setObjectName(_fromUtf8("UI_taxonLayer"))
        self.gridLayout_4.addWidget(self.UI_taxonLayer, 3, 0, 1, 2)
        self.label_111 = QtGui.QLabel(self.groupBox2)
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.gridLayout_4.addWidget(self.label_111, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.UI_projectSelection = QtGui.QComboBox(self.groupBox2)
        self.UI_projectSelection.setObjectName(_fromUtf8("UI_projectSelection"))
        self.gridLayout_4.addWidget(self.UI_projectSelection, 1, 0, 1, 2)
        self.UI_iterationField = QtGui.QComboBox(self.groupBox2)
        self.UI_iterationField.setObjectName(_fromUtf8("UI_iterationField"))
        self.gridLayout_4.addWidget(self.UI_iterationField, 5, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 4, 0, 1, 1)
        self.UI_descriptionField = QtGui.QComboBox(self.groupBox2)
        self.UI_descriptionField.setObjectName(_fromUtf8("UI_descriptionField"))
        self.gridLayout_4.addWidget(self.UI_descriptionField, 5, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 4, 1, 1, 1)
        self.UI_whereEditable = QtGui.QLineEdit(self.groupBox2)
        self.UI_whereEditable.setObjectName(_fromUtf8("UI_whereEditable"))
        self.gridLayout_4.addWidget(self.UI_whereEditable, 7, 0, 1, 2)
        self.gridLayout_9.addWidget(self.groupBox2, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.mGroupBox, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_mapgenerator)
        self.tabWidget.addTab(self.tab_mapgenerator, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_10 = QtGui.QGridLayout(self.widget)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1)
        self.UI_exportPath = QtGui.QLineEdit(self.widget)
        self.UI_exportPath.setObjectName(_fromUtf8("UI_exportPath"))
        self.gridLayout_10.addWidget(self.UI_exportPath, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem5, 4, 0, 1, 1)
        self.UI_exportPathButton = QtGui.QToolButton(self.widget)
        self.UI_exportPathButton.setObjectName(_fromUtf8("UI_exportPathButton"))
        self.gridLayout_10.addWidget(self.UI_exportPathButton, 1, 1, 1, 1)
        self.UI_exportButton = QtGui.QPushButton(self.widget)
        self.UI_exportButton.setObjectName(_fromUtf8("UI_exportButton"))
        self.gridLayout_10.addWidget(self.UI_exportButton, 3, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.widget)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.verticalLayout_121 = QtGui.QVBoxLayout()
        self.verticalLayout_121.setObjectName(_fromUtf8("verticalLayout_121"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_121.addWidget(self.label_10)
        self.UI_logViewPlugin = QtGui.QTextEdit(self.tab_2)
        self.UI_logViewPlugin.setReadOnly(True)
        self.UI_logViewPlugin.setObjectName(_fromUtf8("UI_logViewPlugin"))
        self.verticalLayout_121.addWidget(self.UI_logViewPlugin)
        self.gridLayout_11.addLayout(self.verticalLayout_121, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(PlantMapDialogBase)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PlantMapDialogBase)
        PlantMapDialogBase.setTabOrder(self.UI_projectName, self.UI_projectDescription)
        PlantMapDialogBase.setTabOrder(self.UI_projectDescription, self.UI_contactName)
        PlantMapDialogBase.setTabOrder(self.UI_contactName, self.UI_contactEmail)
        PlantMapDialogBase.setTabOrder(self.UI_contactEmail, self.UI_cbnOrganisation)
        PlantMapDialogBase.setTabOrder(self.UI_cbnOrganisation, self.UI_startDate)
        PlantMapDialogBase.setTabOrder(self.UI_startDate, self.UI_endDate)
        PlantMapDialogBase.setTabOrder(self.UI_endDate, self.UI_projectVersion)
        PlantMapDialogBase.setTabOrder(self.UI_projectVersion, self.UI_thesaurusISO)
        PlantMapDialogBase.setTabOrder(self.UI_thesaurusISO, self.UI_thesaurusInspire)
        PlantMapDialogBase.setTabOrder(self.UI_thesaurusInspire, self.UI_keywords)
        PlantMapDialogBase.setTabOrder(self.UI_keywords, self.UI_contact)
        PlantMapDialogBase.setTabOrder(self.UI_contact, self.UI_dataOwner)
        PlantMapDialogBase.setTabOrder(self.UI_dataOwner, self.UI_genealogyData)
        PlantMapDialogBase.setTabOrder(self.UI_genealogyData, self.UI_cbnManager)
        PlantMapDialogBase.setTabOrder(self.UI_cbnManager, self.UI_updateFrequency)
        PlantMapDialogBase.setTabOrder(self.UI_updateFrequency, self.UI_usageLimit)
        PlantMapDialogBase.setTabOrder(self.UI_usageLimit, self.UI_dataState)
        PlantMapDialogBase.setTabOrder(self.UI_dataState, self.UI_buttonCreate)
        PlantMapDialogBase.setTabOrder(self.UI_buttonCreate, self.UI_buttonPrevious)
        PlantMapDialogBase.setTabOrder(self.UI_buttonPrevious, self.UI_logViewPlugin)
        PlantMapDialogBase.setTabOrder(self.UI_logViewPlugin, self.tabWidget)
        PlantMapDialogBase.setTabOrder(self.tabWidget, self.mGroupBox_2)
        PlantMapDialogBase.setTabOrder(self.mGroupBox_2, self.UI_comboProjectSelection)
        PlantMapDialogBase.setTabOrder(self.UI_comboProjectSelection, self.UI_tabProject)
        PlantMapDialogBase.setTabOrder(self.UI_tabProject, self.UI_validationProject)
        PlantMapDialogBase.setTabOrder(self.UI_validationProject, self.UI_cancelProject)
        PlantMapDialogBase.setTabOrder(self.UI_cancelProject, self.UI_taxonTab)
        PlantMapDialogBase.setTabOrder(self.UI_taxonTab, self.mGroupBox)
        PlantMapDialogBase.setTabOrder(self.mGroupBox, self.UI_exportPath)
        PlantMapDialogBase.setTabOrder(self.UI_exportPath, self.UI_exportButton)
        PlantMapDialogBase.setTabOrder(self.UI_exportButton, self.UI_projectSelection)
        PlantMapDialogBase.setTabOrder(self.UI_projectSelection, self.UI_taxonLayer)
        PlantMapDialogBase.setTabOrder(self.UI_taxonLayer, self.UI_iterationField)
        PlantMapDialogBase.setTabOrder(self.UI_iterationField, self.UI_descriptionField)
        PlantMapDialogBase.setTabOrder(self.UI_descriptionField, self.UI_whereEditable)
        PlantMapDialogBase.setTabOrder(self.UI_whereEditable, self.UI_taxonID)
        PlantMapDialogBase.setTabOrder(self.UI_taxonID, self.UI_validateTaxonID)
        PlantMapDialogBase.setTabOrder(self.UI_validateTaxonID, self.UI_validateTaxonList)
        PlantMapDialogBase.setTabOrder(self.UI_validateTaxonList, self.UI_buttonRemoveAll)
        PlantMapDialogBase.setTabOrder(self.UI_buttonRemoveAll, self.UI_deepValidation)
        PlantMapDialogBase.setTabOrder(self.UI_deepValidation, self.UI_composerName)
        PlantMapDialogBase.setTabOrder(self.UI_composerName, self.UI_extensionMap)
        PlantMapDialogBase.setTabOrder(self.UI_extensionMap, self.UI_mapName)
        PlantMapDialogBase.setTabOrder(self.UI_mapName, self.UI_storagePath)
        PlantMapDialogBase.setTabOrder(self.UI_storagePath, self.UI_storagePathButton)
        PlantMapDialogBase.setTabOrder(self.UI_storagePathButton, self.UI_generateMapButton)
        PlantMapDialogBase.setTabOrder(self.UI_generateMapButton, self.UI_buttonCreateProjectFrom)
        PlantMapDialogBase.setTabOrder(self.UI_buttonCreateProjectFrom, self.UI_buttonCreateProject)
        PlantMapDialogBase.setTabOrder(self.UI_buttonCreateProject, self.UI_buttonEditProject)
        PlantMapDialogBase.setTabOrder(self.UI_buttonEditProject, self.UI_dataGeneaology)
        PlantMapDialogBase.setTabOrder(self.UI_dataGeneaology, self.textEdit)
        PlantMapDialogBase.setTabOrder(self.textEdit, self.scrollArea)
        PlantMapDialogBase.setTabOrder(self.scrollArea, self.UI_exportPathButton)

    def retranslateUi(self, PlantMapDialogBase):
        PlantMapDialogBase.setWindowTitle(QtGui.QApplication.translate("PlantMapDialogBase", "PlantMap : Map Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("PlantMapDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Bienvenue sur le plugin PlantMap : Map Generator</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Ce plugin a pour objectif de générer un grand nombre de cartes. Il permet d\'itérer sur une couche en fonction d\'une liste de valeurs entrée en paramètre. Le mécanisme de génération repose sur la modification du filtre QGIS.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Le filtrage appliquée sur la couche du projet QGIS ne sera pas maintenue lors de la génération. Le champ &quot;filtrage complémentaire&quot; permet d\'appliquer lors de la génération un filtrage supplémentaire sur votre couche.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Les pré-requis :</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">    - Un projet QGS</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">    - Une couche vectorielle </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">    - Un composer intégré au projet</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Ce projet a été réalisé dans le cadre d\'un projet de fin d\'année à l\'</span><a href=\"http://esipe.u-pem.fr/\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; text-decoration: underline; color:#0000ff;\">ESIPE</span></a><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\"> (Ecole Supérieur d\'Ingénieur Paris Est) pour le compte de la </span><a href=\"http://www.fcbn.fr/\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; text-decoration: underline; color:#0000ff;\">FCBN </span></a><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">(Fédération des Conservatoires Botaniques Nationaux).</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Liens annexes :</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">    - </span><a href=\"http://siflore.fcbn.fr\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; text-decoration: underline; color:#0000ff;\">siflore</span></a></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">    - </span><a href=\"https://github.com/Max77T/plantmap-pluginr\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; text-decoration: underline; color:#0000ff;\">GitHub</span></a></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">    - </span><a href=\"http://www.qgis.org\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; text-decoration: underline; color:#0000ff;\">QGIS</span></a></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; text-decoration: underline; color:#0000ff;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; text-decoration: underline; color:#0000ff;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_buttonCreateProjectFrom.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Création d\'un projet à partir d\'un existant", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_buttonCreateProject.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Création d\'un projet", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_buttonEditProject.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Edition de projet existant", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("PlantMapDialogBase", "Description du projet :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Nom contact :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Organisme CBN :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Email contact :", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_contactEmail.setStatusTip(QtGui.QApplication.translate("PlantMapDialogBase", "email", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Nom du projet :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Période d\'étude :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Description projet : ", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(0, QtGui.QApplication.translate("PlantMapDialogBase", "FCBN", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(1, QtGui.QApplication.translate("PlantMapDialogBase", "CBN de Bailleul", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(2, QtGui.QApplication.translate("PlantMapDialogBase", "CBN de Franche-Comté", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(3, QtGui.QApplication.translate("PlantMapDialogBase", "CBN de Corse", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(4, QtGui.QApplication.translate("PlantMapDialogBase", "CBN du Bassin parisien", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(5, QtGui.QApplication.translate("PlantMapDialogBase", "CBN Méditerranéen de Porquerolles", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(6, QtGui.QApplication.translate("PlantMapDialogBase", "CBN Alpin", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(7, QtGui.QApplication.translate("PlantMapDialogBase", "CBN Nord-Est", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(8, QtGui.QApplication.translate("PlantMapDialogBase", "CBN Sud-Atlantique", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(9, QtGui.QApplication.translate("PlantMapDialogBase", "CBN de Brest", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(10, QtGui.QApplication.translate("PlantMapDialogBase", "CBN des Pyrénées et de Midi-Pyrénées", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(11, QtGui.QApplication.translate("PlantMapDialogBase", "CBN du Massif Central", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(12, QtGui.QApplication.translate("PlantMapDialogBase", "CBN Mascarin", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(13, QtGui.QApplication.translate("PlantMapDialogBase", "CB des Iles de Guadeloupe", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(14, QtGui.QApplication.translate("PlantMapDialogBase", "CB de Guyane", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cbnOrganisation.setItemText(15, QtGui.QApplication.translate("PlantMapDialogBase", "CB de Martinique", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Version du projet :", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("PlantMapDialogBase", "Champ insipire", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Thésaurus ISO :", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(0, QtGui.QApplication.translate("PlantMapDialogBase", "Environnement", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(1, QtGui.QApplication.translate("PlantMapDialogBase", "Agriculture", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(2, QtGui.QApplication.translate("PlantMapDialogBase", "Biologie", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(3, QtGui.QApplication.translate("PlantMapDialogBase", "Limites", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(4, QtGui.QApplication.translate("PlantMapDialogBase", "Climatologie et météologie", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(5, QtGui.QApplication.translate("PlantMapDialogBase", "Economie", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(6, QtGui.QApplication.translate("PlantMapDialogBase", "Indiations altimétriques", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(7, QtGui.QApplication.translate("PlantMapDialogBase", "Sciences de la Terre", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(8, QtGui.QApplication.translate("PlantMapDialogBase", "Santé", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(9, QtGui.QApplication.translate("PlantMapDialogBase", "Images et cartes de base", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(10, QtGui.QApplication.translate("PlantMapDialogBase", "Armée et renseignement", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(11, QtGui.QApplication.translate("PlantMapDialogBase", "Cours d\'eau intérieurs", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(12, QtGui.QApplication.translate("PlantMapDialogBase", "Indications de lieux", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(13, QtGui.QApplication.translate("PlantMapDialogBase", "Mers et océans", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(14, QtGui.QApplication.translate("PlantMapDialogBase", "Aménagement du territoire et cadastre", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(15, QtGui.QApplication.translate("PlantMapDialogBase", "Société", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(16, QtGui.QApplication.translate("PlantMapDialogBase", "Subdivisions", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(17, QtGui.QApplication.translate("PlantMapDialogBase", "Transport", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusISO.setItemText(18, QtGui.QApplication.translate("PlantMapDialogBase", "Infrastructures de transport", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Thésaurus Inspire :", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(0, QtGui.QApplication.translate("PlantMapDialogBase", "Répartition des espèces", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(1, QtGui.QApplication.translate("PlantMapDialogBase", "Adresses", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(2, QtGui.QApplication.translate("PlantMapDialogBase", "Altitude", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(3, QtGui.QApplication.translate("PlantMapDialogBase", "Batiments", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(4, QtGui.QApplication.translate("PlantMapDialogBase", "Caractéristiques géographiques météorologiques", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(5, QtGui.QApplication.translate("PlantMapDialogBase", "Caractéristiques géographiques océaniques", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(6, QtGui.QApplication.translate("PlantMapDialogBase", "Conditions atmosphériques", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(7, QtGui.QApplication.translate("PlantMapDialogBase", "Dénominations géographiques", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(8, QtGui.QApplication.translate("PlantMapDialogBase", "Géologie", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(9, QtGui.QApplication.translate("PlantMapDialogBase", "Habitats et biotopes", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(10, QtGui.QApplication.translate("PlantMapDialogBase", "Hydrographie", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(11, QtGui.QApplication.translate("PlantMapDialogBase", "Installations agricoles et aquacoles", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(12, QtGui.QApplication.translate("PlantMapDialogBase", "Installations de suivi environnemental", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(13, QtGui.QApplication.translate("PlantMapDialogBase", "Lieux de production et sites industriels", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(14, QtGui.QApplication.translate("PlantMapDialogBase", "Occupation des terres", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(15, QtGui.QApplication.translate("PlantMapDialogBase", "Ortho-imagerie", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(16, QtGui.QApplication.translate("PlantMapDialogBase", "Parcelles cadastrales", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(17, QtGui.QApplication.translate("PlantMapDialogBase", "Ressources minérales", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(18, QtGui.QApplication.translate("PlantMapDialogBase", "Référentiels de coordonnées", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(19, QtGui.QApplication.translate("PlantMapDialogBase", "Régions biogéographiques", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(20, QtGui.QApplication.translate("PlantMapDialogBase", "Régions maritimes", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(21, QtGui.QApplication.translate("PlantMapDialogBase", "Répartition de la population — démographie", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(22, QtGui.QApplication.translate("PlantMapDialogBase", "Réseaux de transport", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(23, QtGui.QApplication.translate("PlantMapDialogBase", "Santé et sécurité des personnes", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(24, QtGui.QApplication.translate("PlantMapDialogBase", "Services d\'utilité publique et services publics", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(25, QtGui.QApplication.translate("PlantMapDialogBase", "Sites protégés", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(26, QtGui.QApplication.translate("PlantMapDialogBase", "Sols", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(27, QtGui.QApplication.translate("PlantMapDialogBase", "Sources d\'énergie", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(28, QtGui.QApplication.translate("PlantMapDialogBase", "Systèmes de maillage géographique", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(29, QtGui.QApplication.translate("PlantMapDialogBase", "Unités administratives", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(30, QtGui.QApplication.translate("PlantMapDialogBase", "Unités statistiques", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(31, QtGui.QApplication.translate("PlantMapDialogBase", "Usage des sols", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(32, QtGui.QApplication.translate("PlantMapDialogBase", "Zones de gestion, de restriction ou de réglementation et unités de déclaration", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_thesaurusInspire.setItemText(33, QtGui.QApplication.translate("PlantMapDialogBase", "Zones à risque naturel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Mots-clés :", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_keywords.setPlaceholderText(QtGui.QApplication.translate("PlantMapDialogBase", "Mots-clés séparés par des virgules", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Contact :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Propriétaire données :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Généalogie de la donnée :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Responsable CBN :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Fréquence de mise à jour :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Limite d\'utilisation :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Etat de la donnée :", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_buttonCreate.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Créer", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_buttonPrevious.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Retour", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("PlantMapDialogBase", "Sélection d\'un projet", None, QtGui.QApplication.UnicodeUTF8))
        item = self.UI_tabProject.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Name", None, QtGui.QApplication.UnicodeUTF8))
        item = self.UI_tabProject.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Valeur", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_validationProject.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_cancelProject.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Retour", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("PlantMapDialogBase", "Edition / Création", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_generateMapButton.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Générer les cartes", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("PlantMapDialogBase", "Liste de taxons :", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_taxonTab.setSortingEnabled(True)
        item = self.UI_taxonTab.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("PlantMapDialogBase", "ID", None, QtGui.QApplication.UnicodeUTF8))
        item = self.UI_taxonTab.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Description", None, QtGui.QApplication.UnicodeUTF8))
        item = self.UI_taxonTab.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Statut", None, QtGui.QApplication.UnicodeUTF8))
        item = self.UI_taxonTab.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Supprimer", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_buttonRemoveAll.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Supprimer tous les taxons", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Gestion des taxons :", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_taxonID.setPlaceholderText(QtGui.QApplication.translate("PlantMapDialogBase", "Ajouter un taxon (ID du taxon)", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_validateTaxonList.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Charger un fichier ...", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_validateTaxonID.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Valider le taxon", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_deepValidation.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Vérif. Avancée", None, QtGui.QApplication.UnicodeUTF8))
        self.mGroupBox_2.setTitle(QtGui.QApplication.translate("PlantMapDialogBase", "Données en sortie", None, QtGui.QApplication.UnicodeUTF8))
        self.label_119.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Format des cartes en sortie :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Choisir un composeur :", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_extensionMap.setItemText(0, QtGui.QApplication.translate("PlantMapDialogBase", "PNG", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_extensionMap.setItemText(1, QtGui.QApplication.translate("PlantMapDialogBase", "JPEG", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_extensionMap.setItemText(2, QtGui.QApplication.translate("PlantMapDialogBase", "TIFF", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_mapName.setPlaceholderText(QtGui.QApplication.translate("PlantMapDialogBase", "Nom des cartes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Nom des cartes en sortie :", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_storagePathButton.setText(QtGui.QApplication.translate("PlantMapDialogBase", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Dossier de stockage :", None, QtGui.QApplication.UnicodeUTF8))
        self.mGroupBox.setTitle(QtGui.QApplication.translate("PlantMapDialogBase", "Données d\'entrées", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Filtrage complémentaire ", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_linkExpression.setText(QtGui.QApplication.translate("PlantMapDialogBase", "(Qgis Doc) ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("PlantMapDialogBase", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_111.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Couche taxon :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Projet :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Champ d\'itération :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Champ de description :", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_whereEditable.setPlaceholderText(QtGui.QApplication.translate("PlantMapDialogBase", "\"MonChamp\" = \'Ma valeur\' AND [...]", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mapgenerator), QtGui.QApplication.translate("PlantMapDialogBase", "Génération de cartes", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Dossier de stockage à exporter :", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_exportPathButton.setText(QtGui.QApplication.translate("PlantMapDialogBase", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.UI_exportButton.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Exporter", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("PlantMapDialogBase", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("PlantMapDialogBase", "Pour plus de logs, consulter le fichier \"log.txt\" présent dans le dossier de génération", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("PlantMapDialogBase", "Log", None, QtGui.QApplication.UnicodeUTF8))

from qgis import gui
